collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8090736460871994
color:
  saturation: 0.7223376713227481
  brandStrength: 0.4450197098776698
  rhythmicContrast: 0.8722156183794141
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.5723589181434363
layout_spectrum: 0.5829787
name: test
